---
linters-settings:
  dupl:
    threshold: 200
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/tbd-paas/platform-bootstrapper
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport  # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/tbd-paas/platform-bootstrapper
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks:
          - argument
          - case
          - condition
          - return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  staticcheck:
    checks:
      - all

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable
  ##  during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goimports
    - gofmt
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

    # POTENTIAL ISSUES: the following are known to have issues and may need to be disabled in the future.
    #                   see 'ISSUES' section below.
    - gci    # many incorrect errors found different between CI pipeline and locally
    - revive # allow const type = value format for defining constants and variables

    # ISSUES: the following have global issues and are disabled.
    # - exhaustruct:      too restrictive on how to define structures
    # - godox:            allow TODOs in code   
    # - gochecknoglobals: kubebuilder uses globals by default; be consistent
    # - gochecknoinits:   kubebuilder uses init by default; be consistent
    # - wrapcheck:        errors will not be exposed externally
    # - goerr113:         errors will not be exposed externally
    # - depguard:         do not want to implement an allow list for packages

    # OVERRIDDEN: the following are overriden due to other linters being enabled.
    # - rowserrcheck
    # - sqlclosecheck
    # - wastedassign
    # - wsl

issues:
  # excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - scopelint
        - dupl
        - gochecknoglobals
        - testpackage
    - path: internal/pkg/resources/generated.go
      linters:
        - dupl
    - path: go.mod
      linters:
        - gomoddirectives
  exclude-dirs: []
