---
version: 2

before:
  hooks:
    - "go mod tidy"

builds:
  # NOTE: this and other references should match the workload configuration in .source
  - id: "cli"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
      - "windows"
      - "darwin"
    main: "./main.go"
    binary: "platform-bootstrapper"
    ldflags:
      - "-s -w -extldflags '-static'"
archives:
  - name_template: '{{ .Binary }}_v{{ .Version }}_{{ tolower .Os }}_{{ if (eq .Arch "amd64") }}x86_64{{ else if (eq .Arch "386") }}i386{{ else }}{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: "windows"
        format: "zip"
    files:
      - "README.md"
      - "LICENSE"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: "asc"
  use: "github"
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'

# TODO: add homebrew tap
# brews:
#   - name: "platform-bootstrapper"
#     repository:
#       owner: "tbd-paas"
#       name: "homebrew-tap"
#       token: "{{ .Env.ORG_HOMEBREW_TAP_GITHUB_TOKEN }}"
#
#     # Git author used to commit to the repository.
#     # Defaults are shown.
#     commit_author:
#       name: "goreleaserbot"
#       email: "goreleaser@tbd-paas.io"
#
#     # Folder inside the repository to put the formula.
#     # Default is the root folder.
#     directory: "Formula"
#
#     # Your app's homepage.
#     # Default is empty.
#     homepage: "https://github.com/tbd-paas"
#
#     # Template of your app's description.
#     # Default is empty.
#     description: "Operator to deploy TBD Platform Bootstrapper."
#
#     # SPDX identifier of your app's license.
#     # Default is empty.
#     license: "Apache-2.0"
#
#     # Setting this will prevent goreleaser to actually try to commit the updated
#     # formula - instead, the formula file will be stored on the dist folder only,
#     # leaving the responsibility of publishing it to the user.
#     # If set to auto, the release will not be uploaded to the homebrew tap
#     # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
#     # Default is false.
#     skip_upload: auto
#
#     # Packages your package depends on.
#     dependencies:
#       - name: kubectl
#
#     install: |-
#       bin.install "platform-bootstrapper"
#
#     # So you can `brew test` your formula.
#     # Default is empty.
#     test: |
#       system "#{bin}/platform-bootstrapper version"
