---
apiVersion: deploy.platform.tbd.io/v1alpha1
kind: PlatformOperators
metadata:
  name: config
  labels:
    app: platform-config-operator
    app.kubernetes.io/component: platform-config-operator
    app.kubernetes.io/name: platform-config-operator
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/version: unstable
    capabilities.tbd.io/capability: platform-config-operator
    capabilities.tbd.io/platform-version: unstable
    capabilities.tbd.io/version: unstable
spec:
  namespace: tbd-operators-system
