commonOverlays:
  - name: "remove all namespace resources"
    query: "$"
    action: delete
    documentQuery:
      - conditions:
          - query: $[?($.kind == "Namespace")]
          
  - name: "add labels"
    query:
      - metadata.labels
    action: merge
    value:
      app.kubernetes.io/managed-by: platform-bootstrapper
      app.kubernetes.io/created-by: platform-bootstrapper

  - name: "add labels to pods"
    query:
      - spec.template.metadata.labels
      - spec.selector.matchLabels
    action: merge
    onMissing:
      action: ignore
    value:
      app.kubernetes.io/managed-by: platform-bootstrapper
      app.kubernetes.io/created-by: platform-bootstrapper

  - name: "platform operator manifests"
    query: "metadata"
    documentQuery:
      - conditions:
          - query: $[?($.kind == "PlatformOperators")]
    action: "merge"
    value:
      name: "config"
      labels:
        app: platform-config-operator
        app.kubernetes.io/component: platform-config-operator
        app.kubernetes.io/name: platform-config-operator
        app.kubernetes.io/part-of: platform
        app.kubernetes.io/version: "{{ .platformVersion }}"
        capabilities.tbd.io/capability: platform-config-operator
        capabilities.tbd.io/platform-version: "{{ .platformVersion }}"
        capabilities.tbd.io/version: "{{ .platformVersion }}"
      annotations:
        operator-builder.nukleros.io/ready-path: ".status.created"
        operator-builder.nukleros.io/ready-value: "true"

  - name: "platform config manifests"
    query: "metadata"
    documentQuery:
      - conditions:
          - query: $[?($.kind == "PlatformConfig")]
    action: "merge"
    value:
      name: "config"
      labels:
        app: platform-config-operator
        app.kubernetes.io/component: platform-config-operator
        app.kubernetes.io/name: platform-config-operator
        app.kubernetes.io/part-of: platform
        app.kubernetes.io/version: "{{ .platformVersion }}"
        capabilities.tbd.io/capability: platform-config-operator
        capabilities.tbd.io/platform-version: "{{ .platformVersion }}"
        capabilities.tbd.io/version: "{{ .platformVersion }}"
      annotations:
        operator-builder.nukleros.io/ready-path: ".status.created"
        operator-builder.nukleros.io/ready-value: "true"

yamlFiles:
  - name: "platform config operator manifests"
    path: "../vendor/operator/manifests.yaml"
    outputPath: "manifests/platform-config-operator.yaml"

  - name: "platform operator manifests"
    path: "../vendor/deploy/deploy_v1alpha1_platformoperators.yaml"
    outputPath: "manifests/platform-operators.yaml"

  - name: "platform config manifests"
    path: "../vendor/deploy/deploy_v1alpha1_platformconfig.yaml"
    outputPath: "manifests/platform-config.yaml"
